import {useEffect,useState,useRef,useCallback} from 'react';
import {Activity,ArrowDownToLine,BriefcaseBusiness,ChartNoAxesCombined,ChevronRight,Clock3,Coins,House,Layers3,LayoutDashboard,Menu,Package,RefreshCw,ShieldAlert,ShoppingBag,SlidersHorizontal,Store,Truck,Users,Volume2,X,type LucideIcon} from 'lucide-react';
import reportData from './data/report.json';
import type {Report} from './types';
import {NavigateContext,ReportNodes} from './components/Report';
const report=reportData as Report;
const icons:Record<string,LucideIcon>={nivel1:LayoutDashboard,comercial:ChartNoAxesCombined,financiero:Coins,compras:ShoppingBag,inventarios:Package,clientes:Users,logistica:Truck,marketing:Volume2,riesgos:ShieldAlert,mayoristahogar:House,mayoristaintorno:Layers3,retailjuj:Store,retailintorno:BriefcaseBusiness};
const getPage=()=>report.pages.some(p=>p.id===location.hash.slice(1))?location.hash.slice(1):'nivel1';
export default function App(){
 const [pageId,setPageId]=useState(getPage);const [filters,setFilters]=useState(Object.fromEntries(Object.entries(report.filters).map(([k,v])=>[k,v.sel])));const [notice,setNotice]=useState('');const [menuOpen,setMenuOpen]=useState(false);const drawer=useRef<HTMLDialogElement>(null);
 const page=report.pages.find(p=>p.id===pageId)!;
 const navigate=useCallback((id:string)=>{if(!report.pages.some(p=>p.id===id))return;location.hash=id;setPageId(id);setMenuOpen(false);window.scrollTo({top:0,behavior:'instant'});},[]);
 useEffect(()=>{const handle=()=>{setPageId(getPage());setMenuOpen(false);};window.addEventListener('hashchange',handle);return()=>window.removeEventListener('hashchange',handle);},[]);
 useEffect(()=>{document.title=`${page.label} · SIDE / JUJ`;},[page.label]);
 useEffect(()=>{if(menuOpen)drawer.current?.showModal();else drawer.current?.close();},[menuOpen]);
 useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(timer);},[notice]);
 useEffect(()=>{const handler=(e:Event)=>setNotice((e as CustomEvent<string>).detail);window.addEventListener('report-notice',handler);return()=>window.removeEventListener('report-notice',handler);},[]);
 function Sidebar(){return <><div className="brand"><div className="brand-symbol"><Layers3 size={26} strokeWidth={1.5}/></div><div><strong>SIDE<span>®</span></strong><small>José Ugalde Jerves</small></div></div><div className="brand-rule"/><nav aria-label="Centros de inteligencia">{['Ejecutivo','Centros de Inteligencia','Unidades de Negocio'].map(group=><div className="nav-group" key={group}><p>{group}</p>{report.pages.filter(p=>p.group===group).map(p=>{const ItemIcon=icons[p.id];return <button key={p.id} aria-current={p.id===pageId?'page':undefined} onClick={()=>navigate(p.id)}><ItemIcon size={17} strokeWidth={1.65}/><span>{p.label}</span>{p.paused?<small>En pausa</small>:p.id===pageId?<ChevronRight size={13}/>:null}</button>;})}</div>)}</nav><div className="sidebar-foot"><div className="client-monogram">J</div><div><strong>JUJ</strong><span>Dirección empresarial</span></div><span className="foot-dot"/></div></>;}
 return <NavigateContext.Provider value={navigate}><a className="skip-link" href="#main" onClick={e=>{e.preventDefault();document.getElementById("main")?.focus();}}>Ir al reporte</a><div className="app-shell"><aside className="sidebar"><Sidebar/></aside><dialog className="mobile-drawer" ref={drawer} onCancel={()=>setMenuOpen(false)} onClick={e=>{if(e.target===drawer.current)setMenuOpen(false);}}><button className="drawer-close" aria-label="Cerrar menú" onClick={()=>setMenuOpen(false)}><X size={20}/></button><Sidebar/></dialog><main id="main" className="workspace" tabIndex={-1}><div className="utility-bar"><div className="breadcrumbs"><button className="mobile-menu icon-button" aria-label="Abrir menú" onClick={()=>setMenuOpen(true)}><Menu size={21}/></button><span>CONTROLPANEL</span><ChevronRight size={12}/><span>{page.group}</span></div><div className="utility-right"><span className="demo-label"><span/>Datos de ejemplo</span><span className="avatar">JUJ</span></div></div><header className="page-header"><div className="page-heading"><div className="page-kicker"><span className="gold-line"/>SIDE / {page.group}</div><h1>{page.label}</h1><p>{page.question}</p></div><div className="header-actions"><div className="updated-time"><Clock3 size={13}/><span>Última actualización: hoy 07:58</span></div><div className="action-buttons"><button className="button secondary" onClick={()=>window.print()}><ArrowDownToLine size={15}/>Exportar</button><button className="button primary" onClick={()=>setNotice('Vista de demostración. La conexión a Odoo se realizará en la siguiente etapa.')}><RefreshCw size={14}/>Actualizar</button></div></div></header><section className="filters" aria-label="Filtros del reporte"><div className="filter-label"><SlidersHorizontal size={14}/><span>Filtros</span></div><div className="filter-controls">{page.filters.map(key=><label className="filter" key={key}><span>{report.filters[key].label}</span><select aria-label={report.filters[key].label} value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})}>{report.filters[key].options.map(o=><option key={o}>{o}</option>)}</select></label>)}</div></section><div className="report-content" key={pageId}><ReportNodes nodes={page.nodes}/><div className="report-footer"><span>SIDE <i>/</i> {page.label}</span><span>JUJ · CONTROL EMPRESARIAL</span></div></div></main></div>{notice&&<div className="toast" role="status"><Activity size={18}/><span>{notice}</span><button aria-label="Cerrar aviso" onClick={()=>setNotice('')}><X size={16}/></button></div>}</NavigateContext.Provider>;
}

